# -*- coding: utf-8 -*-
"""07-Pandas-Exercises.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R1hIc-qPNyjRu2wULXKZHD3h5QQOQ2Vg

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Copyright Pierian Data</em></center>
<center><em>For more information, visit us at <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# Pandas Exercises

**Source of the Data: https://www.kaggle.com/chirin/africa-economic-banking-and-systemic-crisis-data/downloads/africa-economic-banking-and-systemic-crisis-data.zip/1**


This dataset is a derivative of Reinhart et. al's Global Financial Stability dataset which can be found online at: https://www.hbs.edu/behavioral-finance-and-financial-stability/data/Pages/global.aspx

The dataset will be valuable to those who seek to understand the dynamics of financial stability within the African context.

Content
The dataset specifically focuses on the Banking, Debt, Financial, Inflation and Systemic Crises that occurred, from 1860 to 2014, in 13 African countries, including: Algeria, Angola, Central African Republic, Ivory Coast, Egypt, Kenya, Mauritius, Morocco, Nigeria, South Africa, Tunisia, Zambia and Zimbabwe.



* caseA     number which denotes a specific country
* cc3A     three letter country code
* country    The name of the country
* year   The year of the observation
* systemic_crisis"0" means that no systemic crisis occurred in the year and "1" means that a systemic crisis occurred in the year.
* exch_usd    The exchange rate of the country vis-a-vis the USD
* domestic_debt_in_default   "0" means that no sovereign domestic debt default occurred in the year and "1" means that a sovereign domestic debt default occurred in the year
* sovereign_external_debt_default  "0" means that no sovereign external debt default occurred in the year and "1" means that a sovereign external debt default occurred in the year
* gdp_weighted_default    The total debt in default vis-a-vis the GDP
* inflation_annual_cpi    The annual CPI Inflation rate
* independence   "0" means "no independence" and "1" means "independence"
* currency_crises  "0" means that no currency crisis occurred in the year and "1" means that a currency crisis occurred in the year
* inflation_crises  "0" means that no inflation crisis occurred in the year and "1" means that an inflation crisis occurred in the year
* banking_crisis"no_crisis" means that no banking crisis occurred in the year and "crisis" means that a banking crisis occurred in the year

---
---
***PLEASE NOTE! THERE ARE MANY,MANY DIFFERENT POSSIBLE SOLUTIONS TO THESE QUESTIONS! PLEASE DON'T POST ASKING IF YOUR SOLUTION IS OK IF ITS DIFFERENT. AS LONG AS YOU GOT THE CORRECT ANSWER IT IS OK!***

---
---
# Complete the Tasks Below
---

**TASK: Import pandas**
"""

# CODE HERE
import pandas as pd



"""**TASK:  Read in the african_econ_crises.csv file that is located under the 01-Crash-Course-Pandas folder. Pay close attention to where the .csv file is located! Please don't post to the QA forums if you can't figure this one out, instead, run our solutions notebook directly to see how its done.**"""

# CODE HERE
df = pd.read_csv('african_econ_crises.csv')



"""**TASK: Display the first 5 rows of the data set**"""

# CODE HERE
df.head()



"""**TASK: How many countries are represented in this data set?**"""

# CODE HERE
df['country'].nunique()



"""**TASK: What are the countries represented in this data set?**"""

# CODE HERE
df.country.unique()



"""**TASK: What country had this highest annual CPI Inflation rate? What was the inflation rate?**"""

# CODE HERE
df.sort_values('inflation_annual_cpi', ascending=False).head(1)

# só o país
df.sort_values('inflation_annual_cpi', ascending=False).head(1)['country']



"""**TASK: In what year did Kenya have its first System Crisis?**"""

# CODE HERE
df[(df['country'] == 'Kenya') & (df['systemic_crisis'] == 1)].sort_values('year').head(1)

# só o ano
df[(df['country'] == 'Kenya') & (df['systemic_crisis'] == 1)].sort_values('year').iloc[0]['year']



"""**TASK: How many yearly systemic crisises have occurred per country?**"""

# CODE HERE
df[df['systemic_crisis'] == 1]['country'].value_counts()

# outra maneira
df[df['systemic_crisis'] == 1].groupby('country').count()['year']



"""**TASK: How many years did  Zimbabwe have a sovereign external debt default occur?** """

# CODE HERE
df[(df['country'] == 'Zimbabwe') & (df['sovereign_external_debt_default'] == 1)]['sovereign_external_debt_default'].sum()

# outra maneira
len(df[(df['country'] == 'Zimbabwe') & (df['sovereign_external_debt_default'] == 1)]) # apenas pq não há repetição de anos



"""**TASK: In what year did Algeria have its highest exchange rate?**"""

# CODE HERE
df[df['country'] == 'Algeria'].sort_values('exch_usd', ascending = False).head(1)

# apenas o ano
df[df['country'] == 'Algeria'].sort_values('exch_usd', ascending = False).iloc[0]['year']

