# -*- coding: utf-8 -*-
"""04-DL-CNN-Assessment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ESz4v-e-tbL146IAONyMekDcGAlMK7NQ

# Deep Learning for Image Classification Assessment


Welcome to your assessment! Follow the instructions in bold below to complete the assessment.

------------

## The Challenge

**Your task is to build an image classifier with Keras and Convolutional Neural Networks for the Fashion MNIST dataset. This data set includes 10 labels of different clothing types with 28 by 28 *grayscale* images. There is a training set of 60,000 images and 10,000 test images.**

    Label	Description
    0	    T-shirt/top
    1	    Trouser
    2	    Pullover
    3	    Dress
    4	    Coat
    5	    Sandal
    6	    Shirt
    7	    Sneaker
    8	    Bag
    9	    Ankle boot
"""

import numpy as np
import pandas as pd
import seaborn as sns

"""## The Data

**TASK 1: Run the code below to download the dataset using Keras.**
"""

from tensorflow.keras.datasets import fashion_mnist

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

"""## Visualizing the Data

**TASK 2: Use matplotlib to view an image from the data set. It can be any image from the data set.**
"""

import matplotlib.pyplot as plt

x_train.shape

plt.imshow(x_train[0], cmap='Blues_r')
plt.show()

"""## Preprocessing the Data

**TASK 3: Normalize the X train and X test data by dividing by the max value of the image arrays.**
"""

x_train.max()

x_train.min()

x_test.max()

x_test.min()

x_train = x_train/255

x_test = x_test/255

"""**Task 4: Reshape the X arrays to include a 4 dimension of the single channel. Similar to what we did for the numbers MNIST data set.**"""

