# -*- coding: utf-8 -*-
"""01-Matplotlib-Basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13vb1ddcP4tCZWrbW1Ym5uGyCGP47Eg35

# Matplotlib Basics
"""

import numpy as np
import pandas as pd

"""## Visualizing Plots"""

import matplotlib.pyplot as plt

# variáveis
x = [0,1,2]
y = [100,200,300]

# plotando
plt.plot(x,y)
plt.show()

"""## Basic Tools"""

housing = pd.DataFrame({'rooms':[1,1,2,2,2,3,3,3],
                       'price':[100,120,190,200,230,310,330,305]})

housing

# scatter plot
plt.scatter(housing['rooms'], housing['price'])
plt.show()

"""## Style Calls"""

# labels e title
plt.plot(x,y)
plt.title('Title', fontsize = 12)
plt.xlabel('X label', fontsize = 10)
plt.ylabel('Y label', fontsize = 10);

# limitando os eixos
plt.plot(x,y)
plt.title('Title', fontsize = 12)
plt.xlabel('X label', fontsize = 10)
plt.ylabel('Y label', fontsize = 10)

# limitando os eixos
plt.xlim(0,2)
plt.ylim(100,300)

# alterando a cor
plt.plot(x,y,color='#4a1031')   # hex color picker on google

# Axis and ticks
plt.xlim(0,2)
plt.ylim(100,300)

# Labeling
plt.title('Title', fontsize = 12)
plt.xlabel('X label', fontsize = 10)
plt.ylabel('Y label', fontsize = 10);

# others parameteres
plt.plot(x,y,color='red', marker='o', markersize=10, linestyle='--')

# Axis and ticks
plt.xlim(0,2)
plt.ylim(100,300)

# Labeling
plt.title('Title', fontsize = 12)
plt.xlabel('X label', fontsize = 10)
plt.ylabel('Y label', fontsize = 10);