# -*- coding: utf-8 -*-
"""02-Code-for-Deployment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hpRNb3Jx1hkVcGJQGkv8_QCMesh8zX_R

# CODE FOR DEPLOYMENT:
"""

from tensorflow.keras.models import load_model
import joblib
import numpy as np

# grab model and scaler
flower_model = load_model("final_iris_model.h5")
flower_scaler = joblib.load("iris_scaler.pkl")

# function definition

def return_prediction(model,scaler,sample_json):
    
    # For larger data features, you should probably write a for loop
    # That builds out this array for you
    
    s_len = sample_json['sepal_length']
    s_wid = sample_json['sepal_width']
    p_len = sample_json['petal_length']
    p_wid = sample_json['petal_width']
    
    flower = [[s_len,s_wid,p_len,p_wid]]
    
    flower = scaler.transform(flower)
    
    classes = np.array(['setosa', 'versicolor', 'virginica'])
    
    class_ind = np.argmax(model.predict(flower), axis=-1)

    # deprecated
    # class_ind = model.predict_classes(flower)
    
    return classes[class_ind][0]

flower_example = {
"sepal_length":5.1,
"sepal_width":3.5,
"petal_length":1.4,
"petal_width":0.2
}

# calling the fuction 
return_prediction(flower_model,flower_scaler,flower_example)